### ISSUE TITLE
[Psy-X] Some ISO9660 compatible CD images might not work

### ISSUE THREAD

**Issue by xcom169** [OpenDriver2/REDRIVER2#102]
Hello All!

I have the SLUS-01161 / SLUS-01318 discs. 

I finished the _convert_cd_fmv_xa.bat . I ran fine, but my  .exe still cannot find the data files in DRIVER2\  .

Am I doing something wrong? 
[REDRIVER2_beta1_Win32.zip](https://github.com/OpenDriver2/REDRIVER2/files/6508363/REDRIVER2_beta1_Win32.zip)

**Comment by SoapyMan** [comment]
Make sure that config file points to valid CD image.

**Comment by xcom169** [comment]
That's correct.
My sha256 is : 
2a1a96a660ef5ddfdbbf43dd731179ad1e16c2dc5bb54ca3a63f756fb052daf9 *Driver2CD1.bin

**Comment by SoapyMan** [comment]
I suggest to try old installation method instead then (which requires to extract CD1 image)

**Comment by SoapyMan** [comment]
Seems like there might be an issue with CD image itself. I'll try to investigate further. From what I remember that game ran fine using CCD, ISO and BIN images.

**Comment by xcom169** [comment]
I tried with a different iso. It's working now.
