### ISSUE TITLE
Translations for subtitles of in-game cutscenes

### ISSUE THREAD

**Issue by viniciin** [OpenDriver2/REDRIVER2#103]
Hello!
I recently discovered this beautiful project that was developed and decided to download it to test it.
For a few hours I suffered to be able to install, but fortunately I managed to do everything right, as a big fan of the saga.
I'm Brazilian and I downloaded a version of the game that has Portuguese subtitles in the cutscenes, and I ran the game, I realized that it has English subtitles during the game's lines, but in the cutscenes the game legend is not showing that was added to the BIN I own, and when I run the emulator they appear normally.. They do not appear on Redriver even though I activate them in the menu ..
Can anyone indicate a solution for the Portuguese subtitles of the cutscenes to return?
Thanks.

**Comment by SoapyMan** [comment]
In-game cutscene subtitles is a unique feature of ReDriver2 and you can help translating it. I have only made them in English as I got a transcript in that language.

You can do that by putting regions with subtitle text in WAV files in XA folder and use AppVeyor dev version to export subtitle files. I can then put additional files into future releases with credit ofc.

**Comment by viniciin** [comment]
> In-game cutscene subtitles is a unique feature of ReDriver2 and you can help translating it. I have only made them in English as I got a transcript in that language.
> 
> You can do that by putting regions with subtitle text in WAV files in XA folder and use AppVeyor dev version to export subtitle files. I can then put additional files into future releases with credit ofc.

Can I remove the translated file from the BIN file I have to add to Redriver? he has the Portuguese translation in the cinematics of the game, like that first scene of Lenny at the bar ..
If so, can you explain to me how I do it?

**Comment by SoapyMan** [comment]
Oh, so you've been talking about Full Motion Videos subtitles...
- There is a bug in beta release (which has been fixed) that prevents displaying subtitles.
- SBN files has to be translated with hex editor so it will be probably left to the OpenDriverEngine project with it's use of SRT subtitles.

Also to be said, I have no intention to make different translations different than originally released for ReD2 and leave work to OpenDriverEngine.

**Comment by viniciin** [comment]
Yes, I was talking about Full Motion Videos hahaha ..
As I am terrible in English, as I understand it is still in the project by OpenDriverEngine? that's it?
Anyway, thank you very much for the clarification friend.

**Comment by Joj4k** [comment]
> Yes, I was talking about Full Motion Videos hahaha ..
> As I am terrible in English, as I understand it is still in the project by OpenDriverEngine? that's it?
> Anyway, thank you very much for the clarification friend.

As far as I know in that Brazilian Portuguese version the translators just edited the videos inside the game. So I think you just need to replace the "FMV" folder from the "Brazilian Version".
