### ISSUE TITLE
REDRIVER2.exe is being detected as a Trojan virus by Windows Defender.

### ISSUE THREAD

**Issue by danielfs0** [OpenDriver2/REDRIVER2#106]
Windows Defender is blocking the game executable, stating that it's a Trojan. This started happening when I updated the game files to the "Beta" update, before it was fine.

I know clearly that it's a false-positive, so I excluded REDRIVER2's folder from the anti-virus scan. I'll leave a screenshot of it below.

![Immagine 2021-05-22 144415](https://user-images.githubusercontent.com/84626973/119227077-8af13f80-bb0c-11eb-831e-0303b62be823.png)

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fSabsik.FL.A!ml&threatid=2147780195

**Comment by SoapyMan** [comment]
Sent to Microsoft.
