### ISSUE TITLE
Mission replays can't be viewed from the replay menu.

### ISSUE THREAD

**Issue by danielfs0** [OpenDriver2/REDRIVER2#108]
The game crashes if you save a replay of a mission and then view it from the replay menu. I tried it with the mission Stake Out, and when I save the replay, then exit the mission and go to the replay menu to view it, it crashes to desktop, displaying the following message. I'm using the latest release.

![screen](https://user-images.githubusercontent.com/84626973/119227493-69915300-bb0e-11eb-903f-dcce20111cf0.png)

And here's the crash dump:

[REDRIVER2.zip](https://github.com/OpenDriver2/REDRIVER2/files/6526438/REDRIVER2.zip)

**Comment by SoapyMan** [comment]
Fixed in e3f17a9
