### ISSUE TITLE
[Improvement] Make the day and weather selection button to be on "continue" by default.

### ISSUE THREAD

**Issue by danielfs0** [OpenDriver2/REDRIVER2#109]
It would be great if the day and weather selection button would stay on "continue" by default, so when you need to play in Take a Ride, you just press three times enter and you're quickly in the game, without using the arrows to select to continue every time.

Right now it stays by default on Time: Day, so if you don't pay attention you will just press enter at the TIme button, making only noise. :P

**Comment by SoapyMan** [comment]
Done in 0f6e320
