### ISSUE TITLE
If you replay Lenny gets Caught through the mission select menu, after you finish it you will play Train Pursuit instead of being left at the main menu.

### ISSUE THREAD

**Issue by danielfs0** [OpenDriver2/REDRIVER2#110]
Another bug I have found. If you finish the last mission of the game, Lenny gets Caught, then after the ending cutscenes are finished, the game instead of leaving you to the main menu instead loads Train Pursuit mission from Chicago.

I'm using the latest release and I skipped the ending cutscenes.

**Comment by SoapyMan** [comment]
Already fixed in #105 105
