### ISSUE TITLE
"Skip Cutscene" feature leads to freeze

### ISSUE THREAD

**Issue by danielfs0** [OpenDriver2/REDRIVER2#111]
If you skip the cutscene of the mission C4 Deal sometimes it leads to a crash. However, there is no error message and the error dump file is not generated. It simply says REDRIVER2.exe has stopped working.

I can't really pinpoint the exact cause of this, because sometimes the cutscene gets skipped without a problem.

**Comment by SoapyMan** [comment]
Might be fixed. Needs testing though. 9975302
