### ISSUE TITLE
Issue with saving cars for "continuable" missions

### ISSUE THREAD

**Issue by Joj4k** [OpenDriver2/REDRIVER2#112]
When I started the mission, the car just jumps away when I accelerate or reverse. Tried many times and every time it does this.

 - ReDriver2 beta 1
 - Windows 10 Pro x64
 - Intel i5-8250u
 - Radeon 535
 
 https://vimeo.com/553996172

Using the NTSC-U v1.1 Disc

**Comment by SoapyMan** [comment]
Hopefully this time it gets fixed by 8953ae0
