### ISSUE TITLE
"Pursue Jericho" time bug

### ISSUE THREAD

**Issue by Joj4k** [OpenDriver2/REDRIVER2#113]
**Describe the bug**
The total time of the mission changes when I reset the mission. Sometimes it gaves me +4min, sometimes ~2:00 and ~1:30. I just started the mission and noticed that.

- ReDriver2 beta 1
- Windows 10 Pro x64
- Intel i5-8250u
- Radeon 535

https://vimeo.com/553996206

Using the NTSC-U v1.1 Disc

**Comment by SoapyMan** [comment]
It's not a bug. Chases has been re-recorded and it indicates length of the chase.

**Comment by Joj4k** [comment]
> It's not a bug. Chases has been re-recorded and it indicates length of the chase.

So the time changes according to the route that Jericho takes with the car?
