### ISSUE TITLE
Save bug in "Beat the train"

### ISSUE THREAD

**Issue by Joj4k** [OpenDriver2/REDRIVER2#114]
I was on "Beat the train" and closed the game (exit in the menu) without ending the mission. When I started the game again, it came on the "Car Bomb" mission even though I didn't finish the previous mission.

**To Reproduce**

1. Go to "Beat the train" Mission
2. Exit the game
3. Start the game again

**Expected behavior**
Return to the "Beat the train" mission when opened up the game again.

- ReDriver2 beta 1
- Windows 10 Pro x64
- Intel i5-8250u
- Radeon 535
- Using the NTSC-U v1.1 Disc

**Comment by SoapyMan** [comment]
Already fixed in PR #105
