### ISSUE TITLE
No credits after ending cutscene

### ISSUE THREAD

**Issue by Joj4k** [OpenDriver2/REDRIVER2#117]
**Describe the bug**
After watching the ending cutscene the game just plays the music and doesnt show the credits.

**Expected behavior**
https://youtu.be/5j2EUNHfpmk?t=151

**Screenshots**
https://vimeo.com/554552446

**Environment and game**
ReDriver2 beta 1
Windows 10 Pro x64
Intel i5-8250u
Radeon 535
Using the NTSC-U v1.1 Disc

**Comment by SoapyMan** [comment]
Please check Beta 2 and reipen if it still occurs.
