### ISSUE TITLE
Car lower than it should be on "Mountain Pass"

### ISSUE THREAD

**Issue by Joj4k** [OpenDriver2/REDRIVER2#118]
**Describe the bug**
The car seems lower and have the wheels in the wrong position in "Mountain Pass" mode. The bug happens in Day or Night.

**To Reproduce**
1. Go to Options > Gameplay > Secret > Mountain Pass > Day/Night
2. See error

**Expected behavior**
![image](https://user-images.githubusercontent.com/18411634/119432495-cf3a3680-bcea-11eb-9e7d-6312a505cdbe.png)

**Screenshots**
Night:
![image](https://user-images.githubusercontent.com/18411634/119432364-9dc16b00-bcea-11eb-8ed8-bf2824c7b916.png)

Day:
![image](https://user-images.githubusercontent.com/18411634/119432451-bdf12a00-bcea-11eb-8235-1e91b765bf32.png)

**Environment and game:**
- ReDriver2 beta 2
- Windows 10 Pro x64
- Intel i5-8250u
- Radeon 535
- Using the NTSC-U v1.1 Disc

**Comment by SoapyMan** [comment]
this is not going to be fixed - models are different in LEV files.

вт, 25 мая 2021 г., 09:41 Joj4k ***@***.***>:
