### ISSUE TITLE
[Dev Vers.] Debug Options has a blank option.

### ISSUE THREAD

**Issue by danielfs0** [OpenDriver2/REDRIVER2#120]
I don't know if the dev version of REDRIVER2 is still supported, but I'll report this issue I have found. In the debug options menu there is a blank button at the top, which if you try to press it won't do nothing. This also happens to the other languages as well.

Here's a screenshot of the problem:
![screen](https://user-images.githubusercontent.com/84626973/119524025-8aabab00-bd7d-11eb-8e82-05cc481b7012.png)

**Comment by SoapyMan** [comment]
DEV version features/bugs is often considered not to use by regular users, this one is not exception. 
Dev menu is also is not translated - and will be not.
