### ISSUE TITLE
[DEV Vers.] Playing missions in this version no longer saves them in the save file.

### ISSUE THREAD

**Issue by danielfs0** [OpenDriver2/REDRIVER2#121]
You can no longer play missions in the dev version and then continue by playing it on the normal version. It seems after the beta update it no longer saves the game.

This needs to be fixed, because either it's useful to skip the game quickly or to skip specific annoying missions (looking at you, Chase the Gunman) and then resume to the normal version. I know, the dev version it's not really meant to do that, but that worked in the versions before the beta update, if it's not intentional - that is.

**Comment by SoapyMan** [comment]
DEV version features/bugs is often considered not to use by regular users, this one is not exception. And it was not meant to save progress.
