### ISSUE TITLE
[Enhancement] Disable HUD Damage/Felony bar when no damage or felony cheat is enabled.

### ISSUE THREAD

**Issue by danielfs0** [OpenDriver2/REDRIVER2#125]
It would be great to have something like in the first Driver, where enabling no damage or no felony cheat would disable the bars from the HUD. I don't know if it was an intentional thing left by Reflections or it was forgotten to reimplement, but it would be nice to have it here, since they're pretty pointless when those two cheats are enabled.

**Comment by SoapyMan** [comment]
This was already implemented but restored back
