### ISSUE TITLE
Unable to get inside vehicles when the Mini Cars cheat is enabled.

### ISSUE THREAD

**Issue by danielfs0** [OpenDriver2/REDRIVER2#126]
I can't get inside any vehicle when the Mini Cars cheat is enabled. I can drive the ones that I spawn already inside, but once I'm out of a car, then I can't get back in. I tried pressing triangle + up and also I tried using R3, but nothing happened.

I'm using Beta 2, by the way.

**Comment by SoapyMan** [comment]
Fixed in 56ba090
