### ISSUE TITLE
The menu map of Rio is glitched.

### ISSUE THREAD

**Issue by danielfs0** [OpenDriver2/REDRIVER2#127]
Since the last update, the menu map of Rio is now glitched like in the picture below, with those squares moving around as I move the map. This doesn't happen in the other cities, and the minimap isn't affected.

I'm using Beta 2.

![screen](https://user-images.githubusercontent.com/84626973/120079065-8ef40300-c0b2-11eb-9c5a-6affdd21c2db.png)

I also want to thank you for your time for addressing those issues!

**Comment by SoapyMan** [comment]
Oh, it does happen when bilinear filtering is off...

**Comment by SoapyMan** [comment]
Fixed in 772a676
