### ISSUE TITLE
Holding the "drop camera" button makes the camera not drop, having a very narrow field of view.

### ISSUE THREAD

**Issue by danielfs0** [OpenDriver2/REDRIVER2#128]
When changing cameras, if you hold the select button while you're in the "drop camera" view mode, you won't drop the camera, having this odd and rather useless point of view camera mode. I don't know if this is an intentional feature.

Here's some examples:

![screen1](https://user-images.githubusercontent.com/84626973/120079637-180c3980-c0b5-11eb-8a1d-fd62b144c189.png)
![screen2](https://user-images.githubusercontent.com/84626973/120079639-18a4d000-c0b5-11eb-927a-8bd9efdaad57.png)

**Comment by SoapyMan** [comment]
That's original feature of the camera, not a bug.
