### ISSUE TITLE
This specific junction in Havana has a civilian navigation problem.

### ISSUE THREAD

**Issue by danielfs0** [OpenDriver2/REDRIVER2#129]
This junction in Havana has a navigation problems for the civilian cars that go from the north to the south of the junction. Specifically, they sometimes turn to the wrong way, going agaist the one way traffic from the crossing road.

They do like this, from the point of view of my screenshots:
1) Have the turn signals turned on the wrong side.
2) Then, do a loop around at the junction and back to the position of enabling the turn signals.
3) Actually turn, going agaist the one way traffic.

![screen3](https://user-images.githubusercontent.com/84626973/120079853-273fb700-c0b6-11eb-85ac-c0d4ab48342e.png)
![screen4](https://user-images.githubusercontent.com/84626973/120079855-29a21100-c0b6-11eb-9a43-8037e56f7234.png)
![screen5](https://user-images.githubusercontent.com/84626973/120079857-2ad33e00-c0b6-11eb-88c9-c74add3f7a63.png)

For the record I didn't notice those vehicles going to the actually right side of the one-way road. They either go straight or turn this way.

I don't know if this affect other junctions like this in Havana, in other cities or this is a specific thing which also happened in the original game, I have no idea.

**Comment by SoapyMan** [comment]
Fixed in 68f9773
