### ISSUE TITLE
Debug Menu

### ISSUE THREAD

**Issue by daninthemix** [OpenDriver2/REDRIVER2#133]
How do you access this?

Please just include it in the release build (either via an argument or just in the normal options menu).

I can't find a developer exe anywhere and I want to play with those debug options!

**Comment by SoapyMan** [comment]
It's not included into Release version. You can find Appveyor build with Dev and Debug executables at https://ci.appveyor.com/project/SoapyMan/redriver2-10jm8 /Current build/VS2019 (or Linux)/Artifacts

**Comment by daninthemix** [comment]
I've grabbed the debug build but that refuses to run:

MSVCP140D.dll was not found
VCRUNTIME140D.dll was not found
ucrtbased.dll was not found

I have installed the VC_redist.x86 linked from your Github.

**Comment by daninthemix** [comment]
Oh never mind I needed REDRIVER2_dev.

Thanks
