### ISSUE TITLE
The game starts at an unplayable state.

### ISSUE THREAD

**Issue by H1Jam** [OpenDriver2/REDRIVER2#134]
The mission "Escape from the Brazilians" starts while the car is burning and already wrecked.
I investigate the Savegame format and realized the "GAME_SAVE_HEADER->MISSION_DATA->SAVED_PLAYER_POS->totaldamage" was "20 4E"; changed it to "00 00" problem solved. A simple solution is to reset the damage before the start of each level.
[progress.dat.txt](https://github.com/OpenDriver2/REDRIVER2/files/6643073/progress.dat.txt)

**Comment by SoapyMan** [comment]
Is that a Beta 2 release has this behaviour?

**Comment by H1Jam** [comment]
Yes, it is the latest version.
REDRIVER2.exe SHA-256 : BB77E4FE268057D913B75A2506A3F0637EB631E53205F37EA5E3BEC03B19D493

**Comment by SoapyMan** [comment]
I generally don't like the SHA-256 etc checks due to builds can be different (i've checked it and have no matches) - so IDK what this particular build it is. Closing this issue.
