### ISSUE TITLE
Optimize installation by 170 MB

### ISSUE THREAD

**Issue by alphaTECH-Aus** [OpenDriver2/REDRIVER2#138]
This is not a bug, but I can't select the "enhancement" label.

The REDRIVER 2 installation utility will extract FMV audio as separate files, however the audio is embedded in the video files so these extra files are useless.

I have tested functionality after deleting the audio files. FMVs still play with audio.

**Comment by SoapyMan** [comment]
This should be related to this project
https://github.com/OpenDriver2/Launcher
