### ISSUE TITLE
The complexity of the game

### ISSUE THREAD

**Issue by EugeniyRUS** [OpenDriver2/REDRIVER2#142]
dear author, is it possible to somehow change the complexity of the game? Especially the mission "chasing the shooter", I couldn't pass this mission in 2005 on ps1, now I can't pass it on your development, although I want to note that the mission has become easier. Is it possible to simplify this mission, for example, a lot of damage in one push of the enemy?

**Comment by SoapyMan** [comment]
I'm only slightly reduced the bounciness when you hit lead car and bugfixed the cop AI, but i'm not intending to change the logic for damaging them.
