### ISSUE TITLE
Separation of game resolution and window resolution?

### ISSUE THREAD

**Issue by TrollDecker** [OpenDriver2/REDRIVER2#144]
So, I'm a weird auld git but would it be possible to separate game resolution from window resolution, so the player can, say, set the game res to 640x480 but still have it fill a 1280x960 window in all its blocky glory?

I know, it sounds weird, but I've never been a fan of seeing 90s-era graphics in today's modern ridonkulous resolutions because the issues that become more visible with that become increasingly distracting. Like I said, I'm a weird auld git who favours Chocolate Doom over GZ and tries to play Duke 3D and Quake in 640x480 or similar. 🤷‍♀️

**Comment by SoapyMan** [comment]
Maybe in the forks but I doubt that I will be adding it here.
