### ISSUE TITLE
I can't setup controls

### ISSUE THREAD

**Issue by Gr33nEyes** [OpenDriver2/REDRIVER2#145]
![image](https://user-images.githubusercontent.com/40704849/129790530-50e1bf3b-29a7-4cfd-8cb7-d0eb2c6d2cf0.png)
Buttons just don't work

**Comment by SoapyMan** [comment]
Launcher is heavily WIP and it's bug reports are accepted in this repo: https://github.com/OpenDriver2/Launcher/
Also, the controller configuration is already implemented though it's not been released yet to public.
