### ISSUE TITLE
On Linux when you fail a mission and try to restart the mission the game crashes totally. 

### ISSUE THREAD

**Issue by xcom169** [OpenDriver2/REDRIVER2#150]
**Describe the bug**
On Linux when you fail a mission and try to restart the mission the game crashes totally. 

**To Reproduce**
1. Start the Game on Linux 
2. Start a new game 
3. Fail the mission
4. Select 'Restart' option 
5. Are you Sure ? Yes 
6. See crash with error : [Psy-X]*** %n in writable segment detected ***

**Expected behavior**
The same mission you start from the beginning. 

**Environment and game (please complete the following information):**
 - Game version RC1 Linux
 - Operating System: Ubuntu 20.04 LTS
 - CPU model AMD Ryzen 2600
 - GPU model  AMD Vega56

**Comment by xcom169** [comment]
Log:
[Psy-X] [CdControlB] - Unimplemented 'CdlSetmode'!
[Psy-X] Running CD thread...
[Psy-X] CD: 'CdlReadS' at 10912
[Psy-X] [D: 'CdlPause'
*** %n in writable segment detected ***
zsh: abort (core dumped)  ./REDRIVER2

**Comment by SoapyMan** [comment]
Thanks, I think I found the bug now
