### ISSUE TITLE
Game crashes on Linux after 1 minute in the first mission

### ISSUE THREAD

**Issue by StephGbzh** [OpenDriver2/REDRIVER2#151]
**Describe the bug**
When running the game on Linux, on the first mission I can drive for around one minute then it crashes with `Segmentation fault (core dumped)`

**To Reproduce**
1. Launch REDRIVER2 > Undercover > start the first mission
2. Drive around for one minute
3. Game crashes
4. As I launched from the command line and the game is not in full screen, I could see just before the crash a bunch of lines suddenly appear like this:

```
[Psy-X] Running CD thread...
[Psy-X] CD: 'CdlReadS' at 8796
[Psy-X] CD: 'CdlReadS' at 10913
[Psy-X] CD: 'CdlPause'
[Psy-X] CD thread work done.
[Psy-X] [CdControlB] - Unimplemented 'CdlSetmode'!
```

And it crashes when trying to go back to a lower value (it's always 10912):

```
[Psy-X] Running CD thread...
[Psy-X] CD: 'CdlReadS' at 10942
[Psy-X] CD: 'CdlPause'
[Psy-X] CD thread work done.
[Psy-X] [CdControlB] - Unimplemented 'CdlSetmode'!
[Psy-X] Running CD thread...
[Psy-X] CD: 'CdlReadS' at 10943
[Psy-X] CD: 'CdlPause'
[Psy-X] CD thread work done.
[Psy-X] [CdControlB] - Unimplemented 'CdlSetmode'!
[Psy-X] Running CD thread...
[Psy-X] CD: 'CdlReadS' at 10944
[Psy-X] CD: 'CdlPause'
[Psy-X] CD thread work done.
[Psy-X] [CdControlB] - Unimplemented 'CdlSetmode'!
[Psy-X] Running CD thread...
[Psy-X] CD: 'CdlReadS' at 10912
Segmentation fault (core dumped)
```

**Expected behavior**
Well, no crash would be nice.

**Screenshots**
Not applicable.

**Environment and game (please complete the following information):**
 - Game version 7.4.597 + SLUS 01161 and 01318
 - Operating System: Ubuntu 21.04
 - CPU model Intel i5-4590
 - GPU model Nvidia GeForce GTX 760

**Additional context**
I tried with the [New installation method](https://github.com/OpenDriver2/REDRIVER2/wiki/Installation-instructions#new-installation-method) and with the [flatpak](https://github.com/OpenDriver2/REDRIVER2/wiki/Installation-instructions#installing-the-flatpak-package) and got the same result.

**Comment by SoapyMan** [comment]
Possibly related to #150, will check that.

**Comment by StephGbzh** [comment]
I tried again with the last RC2 release
https://github.com/OpenDriver2/REDRIVER2/releases/tag/7.4-rc2

`REDRIVER2 7.4.693 Feb  4 2022 18:35:52 (Debug)`

But I still get the exact same crash in the same conditions

```
[Psy-X] CD: 'CdlPause'
[Psy-X] CD thread work done.
[Psy-X] [CdControlB] - Unimplemented 'CdlSetmode'!
[Psy-X] Running CD thread...
[Psy-X] CD: 'CdlReadS' at 10944
All SPOOL requests (1) completed successfully on MISC
[Psy-X] CD: 'CdlPause'
[Psy-X] CD thread work done.
[Psy-X] [CdControlB] - Unimplemented 'CdlSetmode'!
[Psy-X] Running CD thread...
[Psy-X] CD: 'CdlReadS' at 10912
Segmentation fault (core dumped)
```

Was the fix included in this release ?

**Comment by SoapyMan** [comment]
Try fully unpacking the game to fix issue.

**Comment by StephGbzh** [comment]
I am not sure what you mean by unpacking ?
Is it about the [tar.gz](https://github.com/OpenDriver2/REDRIVER2/releases/download/7.4-rc2/REDRIVER2_Linux_Release.tar.gz) ?

I tried with both the flatpak version and this linux tar.gz version.
In both cases, I dumped the bin + cue files in the install folder, ran `./_convert_cd_fmv_xa.sh` and then `./REDRIVER2`
Both had the same problem.

**Comment by danger89** [comment]
@SoapyMan Reopen issue. It has not been solved. I can easily reproduce this problem.

```
[Thread 0xdd1ffb40 (LWP 392770) exited]
[Psy-X] [CdControlB] - Unimplemented 'CdlSetmode'!
[New Thread 0xdd1ffb40 (LWP 392771)]
[Psy-X] Running CD thread...
[Psy-X] CD: 'CdlReadS' at 10941
[Psy-X] CD: 'CdlPause'
[Psy-X] CD thread work done.
[Thread 0xdd1ffb40 (LWP 392771) exited]
[Psy-X] [CdControlB] - Unimplemented 'CdlSetmode'!
[New Thread 0xdd1ffb40 (LWP 392773)]
[Psy-X] Running CD thread...
[Psy-X] CD: 'CdlReadS' at 10942
[Psy-X] CD: 'CdlPause'
[Psy-X] CD thread work done.
[Thread 0xdd1ffb40 (LWP 392773) exited]
[Psy-X] [CdControlB] - Unimplemented 'CdlSetmode'!
[New Thread 0xdd1ffb40 (LWP 392774)]
[Psy-X] Running CD thread...
[Psy-X] CD: 'CdlReadS' at 10943
[Psy-X] CD: 'CdlPause'
[Psy-X] CD thread work done.
[Thread 0xdd1ffb40 (LWP 392774) exited]
[Psy-X] [CdControlB] - Unimplemented 'CdlSetmode'!
[New Thread 0xdd1ffb40 (LWP 392775)]
[Psy-X] Running CD thread...
[Psy-X] CD: 'CdlReadS' at 10944
[Psy-X] CD: 'CdlPause'
[Psy-X] CD thread work done.
[Thread 0xdd1ffb40 (LWP 392775) exited]
[Psy-X] [CdControlB] - Unimplemented 'CdlSetmode'!
[New Thread 0xdd1ffb40 (LWP 392776)]
[Psy-X] Running CD thread...
[Psy-X] CD: 'CdlReadS' at 10912
[Psy-X] CD: 'CdlPause'
*** %n in writable segment detected ***
--Type <RET> for more, q to quit, c to continue without paging--

Thread 65 "CDSpooler" received signal SIGABRT, Aborted.
[Switching to Thread 0xdd1ffb40 (LWP 392776)]
0xf7fd0b49 in __kernel_vsyscall ()
```

[debug00.log](https://github.com/OpenDriver2/REDRIVER2/files/8105076/debug00.log)
[index.log](https://github.com/OpenDriver2/REDRIVER2/files/8105077/index.log)
[REDRIVER2.log](https://github.com/OpenDriver2/REDRIVER2/files/8105074/REDRIVER2.log)

**Comment by jonasricardo** [comment]
same problem here
