### ISSUE TITLE
Installation completes but there is no REDRIVER2 file

### ISSUE THREAD

**Issue by llanosCoder** [OpenDriver2/REDRIVER2#152]
Hi,

I followed all the steps and when I ran _convert_cd_fmv_xa.bat it didn't throw any errors or warnings. However, when it finishes I don't find the REDRIVER2 file to run the game. I have not changed anything in the config file since the cdfs points to the right file.

I installed it on Windows 10

![imagen](https://user-images.githubusercontent.com/14224599/133470470-29cc2456-a2ff-45cb-b4d0-ce89a7debd2b.png)

**Comment by SoapyMan** [comment]
@llanosCoder If you use Launcher it might not work with REDRIVER2_dev version. Extract non-dev REDRIVER2 archive into folder. It should contain REDRIVER2.exe

**Comment by llanosCoder** [comment]
Where do I find the non dev version? I downloaded the master branch

**Comment by SoapyMan** [comment]
Please look at [Releases](https://github.com/OpenDriver2/REDRIVER2/releases)

**Comment by llanosCoder** [comment]
Thanks, I understand now. I used the launcher and had no issues.
