### ISSUE TITLE
Texture with no collision

### ISSUE THREAD

**Issue by Kent00734** [OpenDriver2/REDRIVER2#156]
Good afternoon.
I found a bug.
In Las Vegas, there is a texture without collisions.

 - Game version: release candidate 1
 - Operating System: Windows 7 64bit
 - CPU model: Intel i5 2500
 - GPU model: Nvidia GTX 1060 6gb

![Безымянный 2](https://user-images.githubusercontent.com/91142072/134196194-1f9c039a-4ee5-4d04-bbed-842a065c0083.png)
![Безымянный](https://user-images.githubusercontent.com/91142072/134196221-501c814b-d3da-48a5-a31c-6004604f07d8.png)

**Comment by SoapyMan** [comment]
Unfortunately this spot doesn't have collision even on PS1, there's nothing I can do about it.
