### ISSUE TITLE
Frame rate drop in fullscreen.

### ISSUE THREAD

**Issue by PrgmrAtHrt** [OpenDriver2/REDRIVER2#158]
**Describe the bug**
When the game is running in fullscreen the game drops to 20 fps. If the game is un-focused or windowed the framerate returns to 30.

**To Reproduce**
1. Run the game.
2. Load any city.

**Expected behavior**
A stable framerate of 30 fps in fullscreen.

**Environment and game (please complete the following information):**
 - Game version: RC1
 - Operating System: Windows 10 Pro x64
 - CPU model: Intel i5-3320m
 - GPU model: Intel HD Graphics 4000

**Additional context**
This issue did not occur in any previous versions of the game.

**Comment by SoapyMan** [comment]
@PrgmrAtHrt do you have display with high refresh rate? Or different than 60hz?

**Comment by PrgmrAtHrt** [comment]
No, my display is 60hz.

**Comment by alireza109** [comment]
hi friends . this issue ( frame rate drop in full screen ) happened to me too . and when i change the size of game window frame rate improves please solve this soapy man . my device is laptop dell d830 and i love old games . i love driver game series and i hope that redriver2 installs well in old computers like mine . In the meantime , this issue appears in driver syndicate too

**Comment by alireza109** [comment]
another thing in my idea to  makes redriver 2 better is that screen resolution and other graphic settings be available in configure window settings that's why  users who play redriver2 and driver syndicate on old computers and laptops enjoy a lot with no decreasing in frame rate or any other issues

**Comment by danger89** [comment]
My framerate is also low in windowed mode under Linux. This game works better within a emulator than using opendriver2 too bad.

**Comment by PrgmrAtHrt** [comment]
Notably, the game runs perfectly when backspace is held.

**Comment by SoapyMan** [comment]
Duplicate as 162 covers it too
