### ISSUE TITLE
How do I actually compile and play this game?

### ISSUE THREAD

**Issue by bmhkb4** [OpenDriver2/REDRIVER2#16]
"Assuming you have compiled the most recent code or got artifacts from Appveyor. "

How do I compile the code?

"Copy DRIVER2 folder from your game CD to location where compiled EXE is located."

So this means I have to have the original PS1 game CD first?

**Comment by SoapyMan** [comment]
If you want it to play just download release [here](https://github.com/OpenDriver2/REDRIVER2/releases)
And yes, you will need original game CD or ISO. Please read the instructions (everything is in release)
