### ISSUE TITLE
[Psy-X] frame rate can be low depending on monitor refresh rate, fullscreen mode and vertical sync settings

### ISSUE THREAD

**Issue by danger89** [OpenDriver2/REDRIVER2#162]
**Describe the bug**

I don't know if you are already aware of this.
But I'm noticing a low frame rate under Linux in general.

**To Reproduce**
1. Play the latest release(s) for Linux (eg. the tar.gz file)
2. Drive around. 
3. Notice the low FPS / low responsiveness of REDRIVER2 in comparison with [Beetle PSX HW](https://docs.libretro.com/library/beetle_psx_hw/) emulator.
 
**Expected behavior**

I expect at least the same / similar FPS rate and responsiveness as with the Beetle PSX HW Emulator under Linux. (ideally better.. but at least the same)

**Screenshots**

**Environment and game (please complete the following information):**
 - Game version: RC1
 - Operating System: Linux Mint 20 (Ubuntu based)
 - CPU model :  AMD Ryzen 7 2700 
 - GPU model: Sapphire NITRO+ Radeon RX Vega64  (using the `amdgpu` kernel driver)

ps. I suspect the psy cross to be the root issue.

**Comment by SoapyMan** [comment]
That's quite a strange problem and It's probably could be debugged on your machine. I'd love to see any profiling details. 

Also need to know how fast game runs when you press BACKSPACE.

**Comment by danger89** [comment]
I was using the release build. Should I download the debug build?

And how to create a profiling file?

**Comment by danger89** [comment]
> I was using the release build. Should I download the debug build?
> 
> And how to create a profiling file?

Anything?

Ps. My display was a TV screen, with 30 FPS. But it felt like 15 FPS with stutter. While looking at my hardware specs, this is the most powerful PC in my house.

**Comment by danger89** [comment]
> Also need to know how fast game runs when you press BACKSPACE.

It runs insanely insanely fast when I hold the backspace button.

I'm running window mode. You updated the title, but I'm not fully convinced yet if pin pointed the root cause already. Until then maybe don't take too much assumptions?

**Comment by SoapyMan** [comment]
The root cause is how Vsync is handled by the PsyCross and it's bound to how OpenGL swap interval works, I just need a programmer with same hardware as you rn who can fix it and make a Pull Request.

**Comment by danger89** [comment]
I can allow you to access via ssh? If that helps you.

Also I'm a software engineer myself. Although I'm not very familiar with this code base.

**Comment by danger89** [comment]
Anyone?

**Comment by PrgmrAtHrt** [comment]
This issue still persists in version 7.4.618

**Comment by danger89** [comment]
> This issue still persists in version 7.4.618

PR is also still open.

**Comment by SoapyMan** [comment]
Added **vsync** option to **config.ini**, tests with on and off would be helpful. If with vsync=0 it is not reproducible - screen refresh rate option will be added (and Vsync will be permanently disabled in windowed mode)

**Comment by danger89** [comment]
Let me test it.

**Comment by PrgmrAtHrt** [comment]
Tested the latest artifact and can confirm that without V-sync turned on, the game runs exactly as it should.

**Comment by SoapyMan** [comment]
> Let me test it. EDIT: Is there a new release RC2 for this?

not yet, but AppVeyor builds are posted
https://ci.appveyor.com/project/SoapyMan/redriver2-10jm8/builds/42334386

**Comment by SoapyMan** [comment]
Fixed, see comment at https://github.com/OpenDriver2/PsyCross/issues/2

**Comment by danger89** [comment]
Very strange. I put the bin/cue files in the install directory.

I run ./_convert_cd_fmv_xa.sh. Every seems fine. It extract all the data from the bin files (both from cd1 and cd2).

After that, I run REDRIVER Linux binary. But it says it can't find the game files!?? 

It says: "Cannot initialize REDRIVER2. Game files not found by folder 'DRIVER2\'. 

Ps. `[Psy-X] Build date: Jan 29 2022:14:02:23`

**Comment by SoapyMan** [comment]
@danger89 the log doesn't seem to be full.

**Comment by danger89** [comment]
The log doesn't reelly give you any useful errors. I could post the full terminal output if you want.

**Comment by SoapyMan** [comment]
Would be good to see the log anyway. Or check your config.ini

**Comment by danger89** [comment]
I didn't modify the config.ini yet. I just wanted to test out the latest version. But I can't get it running (again giving the error Game files not found by folder 'DRIVER2\',as a popup).

Give me a sec. I will post the full log.

**Comment by danger89** [comment]
```
REDRIVER2_Release_dev$ ./REDRIVER2_dev 
[Psy-X] Initialising Psy-X 2.8
[Psy-X] Build date: Jan 29 2022:14:02:23
[Psy-X] *Video adapter: Radeon RX Vega (VEGA10, DRM 3.41.0, 5.13.0-27-generic, LLVM 13.0.0) by AMD
[Psy-X] *OpenGL version: 4.6 (Core Profile) Mesa 21.3.5 - kisak-mesa PPA
[Psy-X] *GLSL version: 4.60
REDRIVER2 7.4.675 Jan 29 2022 14:02:49 (Release_dev)
[Psy-X] found sound device: OpenAL Soft
[Psy-X] PSX SPU effects are supported and initialized
---- LOG CLOSED ----
AL lib: (EE) alc_cleanup: 1 device not closed
```

[debug00.log](https://github.com/OpenDriver2/REDRIVER2/files/7964518/debug00.log)
[index.log](https://github.com/OpenDriver2/REDRIVER2/files/7964519/index.log)
[REDRIVER2.log](https://github.com/OpenDriver2/REDRIVER2/files/7964520/
[save.log](https://github.com/OpenDriver2/REDRIVER2/files/7964522/save.log)
REDRIVER2.log)

**Comment by SoapyMan** [comment]
Please check `config.ini` for `cdfs` section `image` parameter. It was commented.
usually it reports like that:
```
[Psy-X] Using 'install/Driver2CD1.bin' image, sector size: 2352, frames: 275199
```

**Comment by danger89** [comment]
> Please check `config.ini` for `cdfs` section `image` parameter. It was commented. usually it reports like that:
> 
> ```
> [Psy-X] Using 'install/Driver2CD1.bin' image, sector size: 2352, frames: 275199
> ```

You are right! This needed to be uncommented. I did not need to do that in the past. Why?

**Comment by danger89** [comment]
That being said, this unreleased version I was testing is not causing any low frame rates (even when `vsync=1`), so that is great news. It solved my initial issue for sure.

**Comment by SoapyMan** [comment]
> Can't you automatically detect this?

Running from CD image is going to be deprecated for ReD2 as it is still may be unstable and soon Linux version of Launcher is going to be completed.

**Comment by danger89** [comment]
> > Can't you automatically detect this?
> 
> Running from CD image is going to be deprecated for ReD2 as it is still may be unstable and soon Linux version of Launcher is going to be completed.

ah so you only need to run the convert once and be done with it 👍🏽 ?

**Comment by awsms** [comment]
> Please check `config.ini` for `cdfs` section `image` parameter. It was commented. usually it reports like that:
> 
> ```
> [Psy-X] Using 'install/Driver2CD1.bin' image, sector size: 2352, frames: 275199
> ```

Wait you actually need the extracted files **and** both .bin discs in order to laucnh the program?
