### ISSUE TITLE
REDRIVER2 still crashes when restarting

### ISSUE THREAD

**Issue by danger89** [OpenDriver2/REDRIVER2#163]
**Describe the bug**

Driving around until you die (backspace can speed up that progress).  
Pressing the restart option will sometimes crash the game. Try at least to restart 3x for example.

See gdb output below.

**To Reproduce**
1. Play & die
2. Restart
3. *CRASH* . sig abort.

**Expected behavior**
No crashes.

**Environment and game (please complete the following information):**
 - Game version: RC1
 - Operating System: Linux Mint 20 (Ubuntu based)
 - CPU model :  AMD Ryzen 7 2700 
 - GPU model: Sapphire NITRO+ Radeon RX Vega64  (using the `amdgpu` kernel driver)

**Additional context**

I tried running `gdb` (too bad the dev executable does NOT HAVE debug symbols?).

Anyway, here is the output of `gdb`:

```
[Psy-X] Running CD thread...
[Psy-X] CD: 'CdlReadS' at 10912
[Psy-X] CD: 'CdlPause'
*** %n in writable segment detected ***
--Type <RET> for more, q to quit, c to continue without paging--

Thread 73 "CDSpooler" received signal SIGABRT, Aborted.
[Switching to Thread 0xd87ffb40 (LWP 37131)]
0xf7fcf549 in __kernel_vsyscall ()

(gdb) bt 30
#0  0xf7fcf549 in __kernel_vsyscall ()
#1  0xf780e4c6 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf77f63f7 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0xf78534ac in ?? () from /lib/i386-linux-gnu/libc.so.6
#4  0xf785350c in __libc_fatal () from /lib/i386-linux-gnu/libc.so.6
#5  0xf7840a17 in ?? () from /lib/i386-linux-gnu/libc.so.6
#6  0xf78efcb6 in __printf_chk () from /lib/i386-linux-gnu/libc.so.6
#7  0x5662314a in ?? ()
#8  0x5660b2ee in ?? ()
#9  0xf7d408fa in ?? () from /lib/i386-linux-gnu/libSDL2-2.0.so.0
#10 0xf7daf37c in ?? () from /lib/i386-linux-gnu/libSDL2-2.0.so.0
#11 0xf779e635 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#12 0xf78e18fa in clone () from /lib/i386-linux-gnu/libc.so.6
```

**Comment by SoapyMan** [comment]
Duplicated by #132

Which is fixed in by PR #147 (commit 0ed4aae3ca24de58b513ad522e8df6deba434d3c)
https://ci.appveyor.com/project/SoapyMan/redriver2-10jm8/builds/41843253/job/7fiesqxsya8wq1yx/artifacts
