### ISSUE TITLE
[PORT/QUESTION/REQUIRE] ReDriver2 PSP port?

### ISSUE THREAD

**Issue by qamichele594** [OpenDriver2/REDRIVER2#168]
This is only an question

**Comment by qamichele594** [comment]
[How caused this GBARunner2 issue from SA1 and SA2 Copyprotection locked out in GBARunner2?](https://github.com/Gericom/GBARunner2/issues/247)

**Comment by SoapyMan** [comment]
*why this issue does look like bot?*
Maybe some time PSP port will appear, don't have resources atm to make a port.
