### ISSUE TITLE
a few suggestions

### ISSUE THREAD

**Issue by justtoask** [OpenDriver2/REDRIVER2#173]
According to [PCGW](https://www.pcgamingwiki.com/wiki/REDRIVER_2) you can only choose between driver 1 and 2 soundtrack, why not add an option for both? And why not add support for soundtrack from the PC port of D1? And is a subtitle editing feature included somewhere to allow for fan translations (unless it's not needed)?

On a side note, if you chose the "Full motion video and audio for cutscenes (java required)" option in the launcher, do I need to do [this](https://github.com/OpenDriver2/REDRIVER2/wiki/Installation-instructions#retrieving-game-video-and-audio) part of the installation instructions? 
I just started with this btw so I might not be aware if some of the things I suggested are already in the game

**Comment by SoapyMan** [comment]
PC version of D1 uses different soundtrack playback. The support of D1 PSX soundtrack comes as experiment as it use same playback system (FastTracker 2 XM modules), streaming from CD or file isn't really planned in this project but in OpenDriverEngine it is already working.
