### ISSUE TITLE
Error building on Linux

### ISSUE THREAD

**Issue by studiesronalds** [OpenDriver2/REDRIVER2#177]
**Describe the bug**
  ```
  ==== Building PsyCross (debug_x86) ====
  ==== Building REDRIVER2 (debug_x86) ====
  DebugOverlay.cpp
  In file included from ../DebugOverlay.cpp:1:0:
  ../Game/driver2.h:4:19: fatal error: types.h: No such file or directory
  compilation terminated.
  REDRIVER2.make:313: recipe for target 'obj/x86/Debug/REDRIVER2/DebugOverlay.o' failed
  make[1]: *** [obj/x86/Debug/REDRIVER2/DebugOverlay.o] Error 1
  Makefile:41: recipe for target 'REDRIVER2' failed
  make: *** [REDRIVER2] Error 2
```

**To Reproduce**
Install all dependencies , add Linux version of `premake5` , run `gen_make2.sh` , go to directory `project_gmake2_linux` and run make

**Expected behavior**
Building project

**Comment by SoapyMan** [comment]
Pull request fixing the build would be helpful. It does build for Ubuntu tho (through Appveyor)

**Comment by matthilde** [comment]
It looks there is no types.h header in Linux (probably that Ubuntu got a symlink or workaround?).
I am not sure what types.h specifically is in that context but it may be the equivalent of <sys/types.h> on Linux or other unix-like environments.

**Comment by lis6502** [comment]
it's due to lack of -i386 development package for libc6, however i am myself struggling with working around this. 
Having x64 Debian 12-ish by standard i i have everything x86_64, including gcc.

**Comment by lis6502** [comment]
now i am stuck - no package provides 'libcd.h'
```
lis6502@e595:~/git/REDRIVER2/src_rebuild$ gcc -m32 DebugOverlay.cpp -I/usr/include/linux/ 
In file included from DebugOverlay.cpp:1:
Game/driver2.h:5:10: fatal error: libcd.h: No such file or directory
    5 | #include <libcd.h>
      |          ^~~~~~~~~
compilation terminated.
```

**Comment by SoapyMan** [comment]
Please check how it's getting built with AppVeyor, also it's better to checkout develop-SoapyMan as linux compatibility been improved here
