### ISSUE TITLE
Is the game supposed to be locked to 30fps?

### ISSUE THREAD

**Issue by Pinkyo2386** [OpenDriver2/REDRIVER2#185]
**Describe the bug**
Drops to 30fps as soon as I spawn in the world. I've tried with v-sync off too and it made no difference

**To Reproduce**
1. Open the game in fullscreen.
2. Launch any mode
3. starts at like 75 then quickly drops to 30 fps

**Expected behavior**
30fps

**Screenshots**

**Environment and game (please complete the following information):**
 - Game version REDRIVER2 release candidate 2
 - Operating System: Windows 11
 - CPU model 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz, 2304 Mhz, 8 Core(s), 16 Logical Processor(s)
 - GPU model Nvidia GTX 3060

**Additional context**
165hz display if that matters

**Comment by SoapyMan** [comment]
Game is locked to the 30 fps. And all the media that told that game runs in 60 fps were not right about it

**Comment by Pinkyo2386** [comment]
> Game is locked to the 30 fps. And all the media that told that game runs in 60 fps were not right about it

Ahh alright, thanks, sucks ppl dont get their facts right
