### ISSUE TITLE
Online modes

### ISSUE THREAD

**Issue by binarygeek119** [OpenDriver2/REDRIVER2#19]
I see it going this way
Self hosted servers
Master server to link all self hosted servers
IP connect link 

Co op missions may have to be heavily edited
Free play 
Vs
Last one standing 
Stunts 
Horse (have to copy stunts)
It's trashed (who can trash there car first)

Custom maps

Play as cops

**Comment by SoapyMan** [comment]
REDRIVER2 will stay in it's state close to original game without dramatical changing the gameplay.
All this features you've been openning might be planned for actual **OpenDriver2** project which is already planned
