### ISSUE TITLE
When opening the game an error message appears

### ISSUE THREAD

**Issue by bugdug-trincado** [OpenDriver2/REDRIVER2#191]
When I open the game a message appears saying: Unable to load language files!

I Downloaded the game using the launcher then opened REDRIVER2.exe and the error message appears.

![image](https://github.com/OpenDriver2/REDRIVER2/assets/118624553/f09dfee5-9862-44eb-b047-e733e446d505)

 - Game version Release Candidate 2
 - Operating System: Windows

I put both the bin and cue files on the install folder, but only renamed the bin

**Comment by SoapyMan** [comment]
Use Setup feature in the launcher, it will unpack game and convert necessary game files.
