### ISSUE TITLE
Unable to load language files error

### ISSUE THREAD

**Issue by dkon70** [OpenDriver2/REDRIVER2#194]
Hi!
I'm having trouble starting the game on Windows 11. I get the error "Unable to load language files".
I used the launcher to unpack disk dumps. The launcher identified the language of the game as English.
Also I tried the way of installation without launcher as described in wiki and got same error.
I got dumps of PAL/EU version SLES-02993 / SLES-12993 that marked in wiki as full supported.

![изображение](https://github.com/OpenDriver2/REDRIVER2/assets/118885666/ea34f5c9-c6ef-4c41-9458-1c5fc43101f0)

Here is the log file:
[Psy-X] Initialising Psy-X 2.8
[Psy-X] Build date: Feb  4 2022:18:29:06
[Psy-X] *Video adapter: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 by NVIDIA Corporation
[Psy-X] *OpenGL version: 3.3.0 NVIDIA 537.58
[Psy-X] *GLSL version: 3.30 NVIDIA via Cg compiler
REDRIVER2 7.4.693 Feb  4 2022 18:29:35 (Release)
[Psy-X] Using '.\install\Driver2CD1.bin' image, sector size: 2352, frames: 274417
[Psy-X] found sound device: OpenAL Soft
[Psy-X] PSX SPU effects are supported and initialized
[Psy-X] Using '.\install\Driver2CD1.bin' image, sector size: 2352, frames: 274417
ERROR! Cannot open language file 'DRIVER2\LANG\EN_GAME.LTXT'!
---- LOG CLOSED ----

**Comment by SoapyMan** [comment]
DRIVER2 folder which is coming with the release must be put in the game root (or where the executables and config are located)
