### ISSUE TITLE
[Bug] Game crashes after opening gate to unlock Las Vegas secret cat

### ISSUE THREAD

**Issue by PPastene** [OpenDriver2/REDRIVER2#33]
When I open the gate to unlock the secret car in Las Vegas, just after showing the unlock area message the game crashes and immediately closes, on console there's no output error  I'm playing on Windows 10 x64 using Driver 2 USA rev 1.0 data with no other further configuration

**Comment by SoapyMan** [comment]
fixed in 9ad8a02
