### ISSUE TITLE
Improve the PC keyboard controls, perhaps let the user choose it's configuration?

### ISSUE THREAD

**Issue by ghost** [OpenDriver2/REDRIVER2#37]
It would be nice if the keyboard controls could be changed into something better than the current configuration. Right now it's quite clunky to play this game if you don't use a gamepad. Perhaps add a .ini file which lets the user choose which key to bind?

Hope this gets improved in the future! Great work nonetheless!
EDIT:  Sorry for the wrong label, the site chose automatically to label it as a bug. Oops!

**Comment by SoapyMan** [comment]
That's in works, thanks

**Comment by SoapyMan** [comment]
You can test it now in PR #38

**Comment by SoapyMan** [comment]
Was fixed.
