### ISSUE TITLE
[Bug] Clipping through Havana's secret car underground entrance, resulting in a Game Over

### ISSUE THREAD

**Issue by FatalitySonicX** [OpenDriver2/REDRIVER2#40]
Hello! I don't know if that was already a known issue but I wanted to report this glitch as it always happened on my end.
![image](https://user-images.githubusercontent.com/75029838/100243217-f1b6e700-2f35-11eb-825e-d1dbbc0da8fa.png)
As soon as I pass a certain point on the ground, I go through and the game ends, while it definitely shows I can land on a lower floor.
I'm not usually looking at the console but lemme know if I need to, just so I can take screenshots of it whenever I clip through the ground. Tho, I can tell I'm playing with the 1.1 version as a base.

**Comment by SoapyMan** [comment]
Hey there! It's a known bug and were described here
https://github.com/OpenDriver2/REDRIVER2/wiki/Game-version-differences

**Comment by FatalitySonicX** [comment]
Oh, I see. Guess I didn't look enough. xD
Thanks for linking me the page for it.
