### ISSUE TITLE
Crash in Havana before "Escape The Ferry" starts

### ISSUE THREAD

**Issue by DangusTaargus** [OpenDriver2/REDRIVER2#41]
After completing the "Find the clue" mission, I watch the ending FMV with the picture of the boat in the glove compartment. The FMV ends, the next level loads, and then after the load finishes the game crashes to desktop. This happens 100% of the time and I effectively can't progress any further.

The game has crashed a few times prior to this, but those were all in game and randomly during play. This is the first time it is happening at exactly the same place each time I run the game.

I followed the install steps completely, and am using an ISO set confirmed to be Rev1, not 1.1, and besides a few random crashes the game has been functioning perfectly until this point. Let me know if there's any other info I can provide that will help fix this.

Lastly, thanks for the hard work! This is an amazing project.

**Comment by SoapyMan** [comment]
have you used special vehicles like trucks etc? Or skipped missions in Dev build?

**Comment by DangusTaargus** [comment]
I did use a truck to beat the Find A Clue mission due to its stronger ramming power? Is that considered a special vehicle? That is the mission last finished now that this crash is happening. I can't answer to the second part - I simply started a new game and am just playing regularly so I haven't done any mission skipping.

**Comment by SoapyMan** [comment]
Fixed in #e3f33cb
