### ISSUE TITLE
AI vehicles inside closed-off areas from the traffic.

### ISSUE THREAD

**Issue by daniel-c910** [OpenDriver2/REDRIVER2#44]
There is a glitch with the AI vehicles in Havana, they now turn inside the church area by clipping through the cemetery gates.
To see this, just simply load Havana in freemode and wait until you see the AI vehicles going inside where they shouldn't.

I'm using the latest version, Alpha 5.4 - I don't know if this is the only enclosed area which the AI vehicles now are getting inside, I'll keep checking out for a while, then I'll update this issue.

![REDRIVER2 01_12_2020 21_08_00](https://user-images.githubusercontent.com/75336421/100792278-b2e3ce00-341a-11eb-833b-f4079974cd7d.png)
![REDRIVER2 01_12_2020 21_08_06](https://user-images.githubusercontent.com/75336421/100792282-b37c6480-341a-11eb-9649-114b4ef16121.png)
![REDRIVER2 01_12_2020 21_08_15](https://user-images.githubusercontent.com/75336421/100792286-b37c6480-341a-11eb-9f3f-e07fe65defbe.png)
![REDRIVER2 01_12_2020 21_08_17](https://user-images.githubusercontent.com/75336421/100792287-b414fb00-341a-11eb-8f8b-23643fd25de7.png)

**Comment by daniel-c910** [comment]
Yep, this also happens in other enclosed areas in Havana as well, for example in the Fortaleza de San Carlos.

![REDRIVER2 01_12_2020 21_34_01](https://user-images.githubusercontent.com/75336421/100793914-24bd1700-341d-11eb-9619-0fe0af6f6f1f.png)
![REDRIVER2 01_12_2020 21_34_11](https://user-images.githubusercontent.com/75336421/100793917-2555ad80-341d-11eb-9e9d-522d5b29c112.png)

**Comment by SoapyMan** [comment]
#46 Here's going to be an appveyor build, can you test if issues are resolved? @daniel-c910

**Comment by daniel-c910** [comment]
Yep, it's fixed! I checked both places, thanks!

![REDRIVER2 02_12_2020 08_58_18](https://user-images.githubusercontent.com/75336421/100845222-30402a80-347d-11eb-8fcb-04c3b7b83881.png)
![REDRIVER2 02_12_2020 09_01_29](https://user-images.githubusercontent.com/75336421/100845225-31715780-347d-11eb-90f3-f5e4f867a2f5.png)
