### ISSUE TITLE
Secret Mini has a glitched horn sound effect.

### ISSUE THREAD

**Issue by ghost** [OpenDriver2/REDRIVER2#45]
Just listen to the small video below, it starts fine then it finishes with a weird cartoon spring-like sound effect, it's quite hilarious.

[My video showcasing this issue.](https://streamable.com/go6lnk)

**Comment by SoapyMan** [comment]
Yeah weird and known bug. I think Reflections got that too since it's caused by elevator sound on Havana secret base. Not loading sound bank with it resolves that issue

**Comment by SoapyMan** [comment]
Fixed in https://github.com/OpenDriver2/REDRIVER2/pull/70/commits/50a60a5e3a2a082a327ceab4c841a5e326d5999f
