### ISSUE TITLE
Skipping "Escape to Ferry" and "Escape the Brazilians" makes the player stuck in the void while having a glitched Jericho playermodel.

### ISSUE THREAD

**Issue by daniel-c910** [OpenDriver2/REDRIVER2#47]
If you skip these two Havana missions (Escape to Ferry and Escape the Brazilians), you will spawn stuck in the void and then the game says that you drowned. The interesting thing is that the game also loads a glitchy Jericho as a playermodel.

I think this happens because the game can't find the last vehicle used in the last mission. Maybe add a failsafe which if a vehicle is not present then use a random car?

I'm using the latest Alpha 5.4 dev. version. You can still skip those missions though if you open the menu quickly before the game over screen.

![REDRIVER2 02_12_2020 09_14_28](https://user-images.githubusercontent.com/75336421/100847355-02a8b080-3480-11eb-8032-0fb031d71660.png)
![REDRIVER2 02_12_2020 09_13_44](https://user-images.githubusercontent.com/75336421/100847376-0ccaaf00-3480-11eb-86fe-d906a1101c8d.png)
![REDRIVER2 02_12_2020 09_15_08](https://user-images.githubusercontent.com/75336421/100847385-0f2d0900-3480-11eb-9bce-929f0c38d92b.png)
![REDRIVER2 02_12_2020 09_15_10](https://user-images.githubusercontent.com/75336421/100847396-10f6cc80-3480-11eb-8116-5f2db3e36299.png)

**Comment by SoapyMan** [comment]
Skipping in general is not allowed to regular users (non-dev version users) and it will be not added as a feature.
