### ISSUE TITLE
If you re-enter the police car that you spawned with, you will get a full felony bar.

### ISSUE THREAD

**Issue by daniel-c910** [OpenDriver2/REDRIVER2#51]
Since it's the vehicle that you spawned with, it means it's your personal one and it doesn't really make sense to have a full felony bar as if you stole a parked police car that you found around the map.

You can check it by choosing a police car in the car select menu, exit and re-enter the vehicle to have the felony bar full.

This bug also happens in regular Driver 2.

**Comment by SoapyMan** [comment]
Fixed in d7e3ef0
