### ISSUE TITLE
Police Sirens sometimes does not play correct sound when in "Film director"

### ISSUE THREAD

**Issue by daniel-c910** [OpenDriver2/REDRIVER2#52]
[As you can see in my video here,](https://www.youtube.com/watch?v=szOeWQG04os) the police sirens doesn't work at all when using the film director on a "Quick Getaway" replay.
However in Survival, Take a Ride and Mission replays they just work fine.

Just make a replay of a Quick Getaway chase and you'll see that the police sirens don't work.

**Comment by SoapyMan** [comment]
In fact sirens are played but it plays different sound.

**Comment by SoapyMan** [comment]
Fixed in 11d02e7
