### ISSUE TITLE
Incorrect behaviour of Havana3DOcclusion leading to incorrect cell object visibility/collision

### ISSUE THREAD

**Issue by ghost** [OpenDriver2/REDRIVER2#57]
If you take one of the two hallways on your left when entering the secret base, you'll find that some parts of it are unsolid. However, the rest of the base is solid and I can manage to get the secret car if I use the usual way.

For the record I'm using the SLUS-01161 / SLUS-01318 NTSC US/English rev 1.0 version of Driver 2.

Check out these three videos to show which specific part is unsolid.
[https://streamable.com/bheh4p](https://streamable.com/bheh4p)
[https://streamable.com/963zpv](https://streamable.com/963zpv)
[https://streamable.com/obnh9l](https://streamable.com/obnh9l)

**Comment by SoapyMan** [comment]
Og game had that problems too, due to hardcoding of it. It has to be done in some better way.

**Comment by Zaphero1** [comment]
In recent versions (after 5.41 at least on my Nvidia card) part of the secret base also turn invisible and have more visual glitches. Like I've seen entire hallways disappear as I drive through them shortly before I clip through the floor, and the little car is just always displayed on top of the platform it's resting on.
![image](https://user-images.githubusercontent.com/19298996/103142884-68274000-46c0-11eb-8322-ee7a011c8848.png)

**Comment by MajorOpossum96** [comment]
I encountered this issue recently on Driver 1.1 - My vehicle fell through the floor to the ocean on two occasions, and I was unable to reach the secret vehicle location.

**Comment by ramires352** [comment]
On version 1.1 as soon as you drive on the ramp into the base the car fall through the floor and is game over. I can`t reach the secret car location

**Comment by SoapyMan** [comment]
@ramires352 Driver 2 1.1 (Greatest Hits / Platinum) has this issue with heightmaps. Beta release will automatically patch game to fix that issue (basically by replacing 1.1 HAVANA.LEV parts with 1.0)

**Comment by SoapyMan** [comment]
85f60b3 973f24f and 1ba93d2 fixing all the related issues
