### ISSUE TITLE
Planting the C4 in "Destroy the Yard" mission leads to a crash.

### ISSUE THREAD

**Issue by daniel-c910** [OpenDriver2/REDRIVER2#60]
I was playing the last Las Vegas mission, Destroy the Yard and when I go to plant the first C4 the games freezes and then crashes.
For the note I had about 50 seconds in the mission timer and I planted the C4 on the truck on your left when entering the building.

I can't get any additional information as the game just simply dies without even leaving the command prompt open. I'm using the latest github release with the version 1.0 NTSC of Driver 2.

I already completed the game, and this is my second run of the story mode. I'm not playing this mission through the Replay Mission list.

**Comment by SoapyMan** [comment]
Try redownloading latest release, it's been fixed

**Comment by daniel-c910** [comment]
Yep, it works alright. I swear I had the latest version though, because last time I updated the game [I used the latest version from the appveyor to check if this bug had been fixed.](https://github.com/OpenDriver2/REDRIVER2/issues/44) Strange.
