### ISSUE TITLE
Wrecking secret cars before unlocking them will lead to a game over screen.

### ISSUE THREAD

**Issue by daniel-c910** [OpenDriver2/REDRIVER2#61]
If you wreck the secret cars before unlocking them will make the game think that you have wrecked your vehicle (which intends the secret car) and then it will lead into a game over screen. This happens even when your vehicle doesn't have any damage at all.

To see this bug happen, go to the Havana secret base, open the door and then drop down in the elevator's hole. Then knock off the Mini down and then wreck it with your car. When the Mini is totalled the game will say game over, even when your normal vehicle doesn't have any damage at all!

This also happens to every secret car of all cities.

**Comment by SoapyMan** [comment]
Well this cannot be fixed as well as this is how mission scripts work

**Comment by SoapyMan** [comment]
This is exactly how original mission script functions because it's one of mission targets
