### ISSUE TITLE
In recent dev builds the Havana Pick Up Truck is very unstable

### ISSUE THREAD

**Issue by Zaphero1** [OpenDriver2/REDRIVER2#62]
Current Dev Build: 5.4.194
I don't know if this is a known issue since the truck flat out crashed the game in dev builds before this one (after the last release build, 5.41), but the pickup truck currently messes up the textures of the environment, turns into a distorted inside out mesh when you start driving, then turns into a bus when you crash into something, and crashes the game when you hit restart or replay. I'm not sure but it also seems like this is the only way to spawn a pickup in the city. I haven't seen a single other one when driving around in recent dev builds.

**Comment by Zaphero1** [comment]
Correction: The game still crashes if you try entering with the pickup in the daytime, it's nighttime where the game lets you go in with that buggy state, and it's entirely possible that this was always the case with recent dev builds but I kept selecting daytime.

**Comment by SoapyMan** [comment]
fixed in 0885965 commit
