### ISSUE TITLE
Starting Game Issue

### ISSUE THREAD

**Issue by nonunknown** [OpenDriver2/REDRIVER2#64]
**Describe the bug**
Getting this error message:
![image](https://user-images.githubusercontent.com/58845030/103140060-f56a9480-46c0-11eb-9855-674672da9531.png)
PS: before this error it says vcruntime140.dll and msvcp140.dll was missing, so i've downloaded them and placed in the folder!

**To Reproduce**
I've followed installation instructions for windows:
* downloaded disc 1 and 2 (according to described ISO ID)
* extracted disc 1 into folder (with Iso software)
* did the same with disc 2 and replaced files
* extracted Redriver:
![image](https://user-images.githubusercontent.com/58845030/103140065-061b0a80-46c1-11eb-88d3-ed2e6b6b7521.png)

**Expected behavior**
Game Starts

**Desktop (please complete the following information):**
Windows 10 x64

**Comment by SoapyMan** [comment]
Seems like you just put 64 bit dlls. You need to properly install VC++ 2019 redistributable x86, download here: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by nonunknown** [comment]
ohhh I had only x64 one :D

but sadly I got other error, when I open window instantly close!
![image](https://user-images.githubusercontent.com/58845030/103140220-e97fd200-46c2-11eb-9352-765ae40a8fcf.png)

**Comment by SoapyMan** [comment]
What's your GPU?

**Comment by nonunknown** [comment]
Intel HD Graphics 3000

**Comment by SoapyMan** [comment]
I think I know the problem. OpenGL 3.3 is not supported by your the video driver but 3.1 is supported. I'll patch the game and will link to the appveyor build once done.

**Comment by SoapyMan** [comment]
@nonunknown try running this: https://ci.appveyor.com/project/SoapyMan/redriver2-10jm8/builds/36999217/job/jyi94essejm8ydbl/artifacts

**Comment by nonunknown** [comment]
this is what I found strange, when I was using linux, I could run godot engine GLES3 and GLES2, and now I'm on windows I can only use GLES2

**Comment by nonunknown** [comment]
> @nonunknown try running this: https://ci.appveyor.com/project/SoapyMan/redriver2-10jm8/builds/36999217/job/jyi94essejm8ydbl/artifacts

Worked flawlessly, although , it is running slow, maybe because my pc isnt fast enought,

btw on epsxe works fine (60fps) so I was thinking maybe adding some menus to options:

* Windowsize (640x480,720x480,....)
* Internal resolution (640x480,720x480)
* Show FPS (on/off)
* Traffic Amount (0-10) //how many cars will spawn close to player
* Render Distance (0-1800) //like the configfile

Internal keymapping and so on!

**Comment by SoapyMan** [comment]
> Worked flawlessly, although , it is running slow, maybe because my pc isnt fast enought,
Nice!
> btw on epsxe works fine (60fps)
Probably on RetroArch it will run slow too as it use same methods for rendering
Render distance is adjustable in config.ini already. PSX default is 441.
