### ISSUE TITLE
[Feature Request] Support for Different size images for textures

### ISSUE THREAD

**Issue by nonunknown** [OpenDriver2/REDRIVER2#66]
I'm trying to change loading screens of the game, when using same as original sizes works fine, but I've tried scaling it 2x, maybe a limitation of TIM format files?

Original:

![LOADCHIC](https://user-images.githubusercontent.com/58845030/103141151-c78c4c80-46ce-11eb-9e8d-9f9599ab9d7c.png)

In-game:
![image](https://user-images.githubusercontent.com/58845030/103141122-72503b00-46ce-11eb-9648-bb1b90cc5586.png)

The solution could be:

* Add support for png/jpeg/bmp images instead of TIM
or
* Add support for larger TIM files

In my humble opinion, Adding support for png images could make easier for HD mods....

**Comment by SoapyMan** [comment]
Not possible with current architecture. REDRIVER2 stays true to the PS1 version (and will be built later back to PS1). All further graphical, sound and engine improvements will be only featured in OpenDriver2 which is already planned.

**Comment by nonunknown** [comment]
oh, nice to know
