### ISSUE TITLE
Add support for new translation into Russian

### ISSUE THREAD

**Issue by free-gen** [OpenDriver2/REDRIVER2#67]
Hi, I am the author of a new translation of this game. Not so long ago I saw your work and immediately rushed to test this project with my translation. To my regret, many letters in the game are displayed incorrectly, since the project apparently uses built-in fonts and text for in-game menus. If possible, please add support for the above localization.
The game itself is available at the link: https://free-gen.github.io/driver2

**Comment by SoapyMan** [comment]
Hey there! Nice to see you there.

The only built-in font for now is a subtitles font. Others like FEFONT and FONT2 can be directly replaced so there should be no problem. Same with the strings - game texts are easily replaceable.

**Comment by SoapyMan** [comment]
@free-gen do you have a source texts or at least converted/remapped ones?

**Comment by free-gen** [comment]
Yes, I can provide any sources.
And about fonts, I put it wrong. I was referring to some menus within the game. The text for them is written in the files SLUS_011.61 (if it is an American version). In REDRIVER2, these files are not used, and this text is apparently taken from some files from your project. That's why I asked to add translation support.
Sources from my translation are here: https://mega.nz/folder/uGpCRCIK#PFXA0Zm_f_YS5uugEWhiYg

**Comment by free-gen** [comment]
UPD - I downloaded the latest update and found that it is now possible to change some of the texts in the game. However, only Latin characters can be entered this way. The Russian alphabet has more characters than the Latin one. Therefore, when I changed the font, I used some unicode characters (such as å â ã).
In the original Greatest Hits game, these characters required Cyrillic and Latin characters. For example, to display the word "Урон" (Damage), you had to enter "Ypoь".
I tried to enter this in the ENGLISH_GAME.LTXT file, but it does not give any results, since the game only displays Latin characters. I tried randomizing unicode characters to figure out which input characters to use so that the game displays the entire Russian font, but whatever I enter, the game displays empty fields.

In the picture below you can see the modified Russian font (above), and the original (below).
How to make the game display all Russian characters correctly?
![image](https://user-images.githubusercontent.com/32083948/103472585-d2d02e00-4dda-11eb-8d12-36bed8ff2447.png)

**Comment by SoapyMan** [comment]
There was bug that didn't allowed to use extended ascii characters, but it was fixed in latest builds, take it from here:
https://ci.appveyor.com/project/SoapyMan/redriver2-10jm8/branch/master/job/fouihgs1s8j113sy/artifacts

**Comment by free-gen** [comment]
when trying to start, a white screen appears and everything freezes. smd reports this:
[Psy-X] PSX SPU effects are supported and initialized
[Psy-X] [ParseCueSheet] - Failed to open disc image file! IMAGE.CUE
[Psy-X] [CdInit] - Failed to read cue sheet!

**Comment by SoapyMan** [comment]
Can you send a full log?

**Comment by free-gen** [comment]
[Psy-X] Initialising Psy-X 1.700
[Psy-X] Build date: Jan  2 2021:21:54:17
[Psy-X] *Video adapter: Intel(R) HD Graphics 4000 by Intel
[Psy-X] *OpenGL version: 3.3.0 - Build 9.17.10.2932
[Psy-X] *GLSL version: 3.30 - Build 9.17.10.2932
[Psy-X] [GR_Shader_CheckShaderStatus] - No errors.

[Psy-X] [GR_Shader_CheckShaderStatus] - No errors.

[Psy-X] [GR_Shader_CheckProgramStatus] - No errors.

[Psy-X] [GR_Shader_CheckShaderStatus] - No errors.

[Psy-X] [GR_Shader_CheckShaderStatus] - No errors.

[Psy-X] [GR_Shader_CheckProgramStatus] - No errors.

[Psy-X] [GR_Shader_CheckShaderStatus] - No errors.

[Psy-X] [GR_Shader_CheckShaderStatus] - No errors.

[Psy-X] [GR_Shader_CheckProgramStatus] - No errors.

[Psy-X] [ParseCueSheet] - Failed to open disc image file! IMAGE.CUE
[Psy-X] [CdInit] - Failed to read cue sheet!
found sound device: OpenAL Soft
[Psy-X] PSX SPU effects are supported and initialized
[Psy-X] [ParseCueSheet] - Failed to open disc image file! IMAGE.CUE
[Psy-X] [CdInit] - Failed to read cue sheet!

I don't build anything. i just downloaded src_rebuild \ bin \ Release \ REDRIVER2_Release.zip
