### ISSUE TITLE
libgs in Psy-X

### ISSUE THREAD

**Issue by mgarcia-org** [OpenDriver2/REDRIVER2#71]
Hi,
This is a very cool project, and the SDK is very neat! :)
Just wondering if Psy-X will include libgs at some stage?

I ask because it would be very use full for Net Yaroze development.
Here is the libgs implementation as used in the net yaroze (and the rest of the SDK):
https://github.com/ChrisRx/mipsel-ecoff-toolchain/blob/master/sdk/include/libps.h

Thanks.
Mike.

**Comment by SoapyMan** [comment]
Hey!
Yes, ideally I would want to include the most of the Playstation API to it including LibGS. Just need to put some research into it.

**Comment by mgarcia-org** [comment]
Very cool :) thanks!
I guess it would be also decompiled too right? or hand built using the Psy-X base?

**Comment by SoapyMan** [comment]
> I guess it would be also decompiled too right? or hand built using the Psy-X base?
Yep, they have to be decompiled at least to get understanding what they have under the hood

**Comment by mgarcia-org** [comment]
Cool thanks :)
I will definitely be using this!
Keep up the good work :+1:
