### ISSUE TITLE
Savegame files

### ISSUE THREAD

**Issue by leonkis** [OpenDriver2/REDRIVER2#72]
Hi, how would one load a savegame file?

**Comment by SoapyMan** [comment]
Game is saved and loaded automatically.
Saved games are located in user profile folder
- %USERPROFILE% on Windows
- Home folder on Linux

Saves and replays from memory cards are not supported.

**Comment by leonkis** [comment]
Thank you very much. Is there any way to unlock Vegas and Rio without actually playing the main story?

**Comment by leonkis** [comment]
In other words, is there any way to use cheats (of the gameshark sort) with Redriver2?

**Comment by SoapyMan** [comment]
> Thank you very much. Is there any way to unlock Vegas and Rio without actually playing the main story?
I would encourage you to complete the game once more for PC. It has some gameplay differences and restored features. Also community recorded some chases for it (despite already outdated due to Civ AI fixes)

> In other words, is there any way to use cheats (of the gameshark sort) with Redriver2?
Existing gameshark codes are not supported.
