### ISSUE TITLE
Going inside a brush - Las Vegas

### ISSUE THREAD

**Issue by BenoitAdam94** [OpenDriver2/REDRIVER2#77]
**Describe the bug**
A brush in Las Vegas seems buggy.

Bug encountered during the mission "Steal The Keys"

**Screenshots**

See at 52:00 of this video :
https://youtu.be/HGoeRX4WR-M?t=3122

**Desktop (please complete the following information):**
 - OS: Windows 7 64 Bits
- REDRIVER 5.7

**Comment by SoapyMan** [comment]
This one especially - an original LEV file bug. 
I was assuming before that heightmaps for Vegas was compiled with low quality of BSP due to fact of limited RAM of PS1.

It is also seen on this exact spot in original PS1 version of the game.
