### ISSUE TITLE
[Gameplay] Add the possibility to add the secret cars unlocked in the savegame state

### ISSUE THREAD

**Issue by revix-0** [OpenDriver2/REDRIVER2#80]
On PSX, once you unlocked the secret cars, the game would not save them in the next game startup, you had to unlock them again, if it's possible, make sure that once the cars are unlocked, are kept in the game save for the next boot.

It's not a bug caused from this program, it's how the game worked back then. Remove the bug label.

**Comment by SoapyMan** [comment]
Yep, auto save of score tables, unlocks and configuration overall will be added soon in Beta.

**Comment by AD010** [comment]
but old games on PC (FPS, Stealth, Strategy) have free save / load
