### ISSUE TITLE
Keyboard control - project not supports NUMPAD keys

### ISSUE THREAD

**Issue by AD010** [OpenDriver2/REDRIVER2#81]
i try config keys to Numeric keyboard, used another variants (like NUM_8, NUMPAD8, NUMPAD_8, Numeric keypad  8, NUM8, NUM 8 etc), but not work, please add support this num keys

**Comment by SoapyMan** [comment]
Try using this as the reference for key names, numpad is actually a Keypad
https://wiki.libsdl.org/SDL_Keycode

**Comment by AD010** [comment]
> 
> 
> Try using this as the reference for key names, numpad is actually a Keypad
> https://wiki.libsdl.org/SDL_Keycode

Thank you, this work
