### ISSUE TITLE
How to extract CD 2 ?

### ISSUE THREAD

**Issue by Gabolinha** [OpenDriver2/REDRIVER2#83]
I am using UltraISO and when I extract the CD 2 it asks to replace files, should I accept it or not?

**Comment by Nandolavras** [comment]
> I am using UltraISO and when I extract the CD 2 it asks to replace files, should I accept it or not?

Yes, simply replace files and continue doing the instructions.

**Comment by Gabolinha** [comment]
Thanks, i play your projeção now and is great, I will send the bugs I find
ok?

Em ter, 9 de mar de 2021 22:26, Nandolavras ***@***.***>
escreveu:

**Comment by SoapyMan** [comment]
Seems like everything resolved.
Please check closed issues before sending the new ones :)
