### ISSUE TITLE
Graphical glitch and crash

### ISSUE THREAD

**Issue by DarkKnight94** [OpenDriver2/REDRIVER2#87]
I installed the game following all the instructions provided on the Github page, using an iso extracted from my original game with release version SLES-02993. After clicking the executable, i come across a glitchy screen which can be found below and then the game window force closes without any error codes. My computer specs are the following:

CPU: Intel I5-7400
Ram: 8GB DDR4 2400MHZ
GPU: Zotac Gtx 1060 3gb AMP!
OS: Windows 10 Home Edition Bulid 2004

![Annotation 2021-03-24 003251](https://user-images.githubusercontent.com/10264420/112227530-7ee62000-8c38-11eb-9421-cda447022e63.jpg)

**Comment by SoapyMan** [comment]
That's weird. Seems like badly extracted data to me. Maybe problem with a CD?
Can you attach a REDRIVER2.log file?

**Comment by DarkKnight94** [comment]
Here is the log file. I noticedit says at some point that "No CUE file is found". The BIN and CUE files have been also placed inside the same folder and the issue persists with an image extractred from my original CD as well as two different downloaded ISOs

[REDRIVER2.log](https://github.com/OpenDriver2/REDRIVER2/files/6200597/REDRIVER2.log)

**Comment by SoapyMan** [comment]
Try extracting different ISO, try using different programs to do so. It seems like a corrupted ata

**Comment by SoapyMan** [comment]
I'll close it for now since there are no players reporting same issue characteristics.
