### ISSUE TITLE
Bus is hugely underpowered !

### ISSUE THREAD

**Issue by SDabdlmounaim96** [OpenDriver2/REDRIVER2#88]
**Describe the bug**
i jumped into re driver 2 for the first time, and as soon as i saw the big yellow bug i knew it was something out of the ordinary since i never seen it as a kid during driver 2

**To Reproduce**
get inside a big yellow bus
hit any car / traffic or police
the bus will have little impact effect as if it was a simple light weight vehicle

i assume it's probably a cut vehicle or something that has been restored improperly without proper weight

**Expected behavior**
i expect to be very powerful when i ride in such a big and strong vehicle, i want to hit traffic and smash cop cars out of m way

**Comment by SoapyMan** [comment]
Alright, but have you played original Driver 2 lately?
Closing this.
