### ISSUE TITLE
Rendering : Z buffer issues?

### ISSUE THREAD

**Issue by rahulroy9202** [OpenDriver2/REDRIVER2#92]
Encountered in Free Ride 

Please take a look at these screenshots. 

![image](https://user-images.githubusercontent.com/3462467/115849726-cbdd3200-a442-11eb-941a-bcde087762e2.png)

![image](https://user-images.githubusercontent.com/3462467/115849822-e3b4b600-a442-11eb-9c2b-2502a7158b90.png)

**Comment by SoapyMan** [comment]
Playstation does not have Z-buffer and Psy-Cross layer (which partially implements PSX graphics)  implements Z-buffer but not for 6.0b and earlier builds of the game.
First screenshot - original game engine limitation and I can do nothing about in in ReD2 - expect fix in OpenDriver2
Second screenshot - seems like you use 6.0b build and Z buffer is still disabled. Use latest AppVeyor builds or edit config.ini

**Comment by rahulroy9202** [comment]
> can do nothing about in in ReD2 - expect fix in OpenDriver2

is ReD2 and OpenDriver2 different ?

**Comment by SoapyMan** [comment]
Yep, those meant to be different projects. ReDriver2 is the close (almost 1:1) recreation of original game code in C from symbols & disassembly while OpenDriver2 (see OpenDriverEngine repo) is the full rewrite of game from scratch to C++
