### ISSUE TITLE
[Improvement] Added some wiki informations

### ISSUE THREAD

**Issue by VinnyVynce** [OpenDriver2/REDRIVER2#93]
Hi 👋🏻 
I added some informations within the wiki to install the Flatpak release on Linux and I also added a installation guide in french as well.  
However I have no clue how to actually do a pull request of the wiki, I think there's a setting within the repo which allow that from what I've gathered. 
Anyway, you can always take my forked wiki and add/merge the changes.
```
git clone https://github.com/VinnyVynce/REDRIVER2.wiki.git
```
Thanks for this fantastic project once again.
cya ✌🏻

**Comment by SoapyMan** [comment]
Done!
Turns out filenames on Windows are invalid :P
