### ISSUE TITLE
[Psy-X] Texture filter switch per polygon (using PSYX_* primitive)

### ISSUE THREAD

**Issue by The-King-of-Toasters** [OpenDriver2/REDRIVER2#96]
The low resolution nature of the HUD and game text doesn't look great when filtered. Short of texture replacements or a nearest neighbour upscale, it would be nice to mark these textures as not needing to be filtered.

**Comment by SoapyMan** [comment]
@The-King-of-Toasters Psy-X already supports Hi-res 32 bit texture replacement and it's made for font and number textures, fonts are in process. But PSX renderer itself should have the filtering switch - maybe some day.

**Comment by SoapyMan** [comment]
No need in that yet. PSX polygons are pretty in their nature (nope, all ugly :P)
