### ISSUE TITLE
Screen covered in green and purple stripes (windowed only)

### ISSUE THREAD

**Issue by qweq12yt** [OpenDriver2/REDRIVER2#98]
![image](https://user-images.githubusercontent.com/45515587/116954875-7a654c00-ac67-11eb-842e-f8b4340c3daa.png)
This is pretty much it, they flicker at what seems to be each time the screen updates (static screen = no flicker). They persist through gameplay, menus, and fmvs. Otherwise the game seems to run fine.

Computer specs are:
- i5-7200U processor
- 8GB Ram
- Intel Integrated Graphics
- Windows 10 x64

**Comment by SoapyMan** [comment]
@qweq12yt This is probably related to the backbuffer format but too strange it happens on the relatively modern hardware. Try checking if your driver has forced anti-aliasing stuff enabled or anything else in control panel.

**Comment by SoapyMan** [comment]
Closed due to no response recieved.
