### ISSUE TITLE
Havana Secret Area broken

### ISSUE THREAD

**Issue by qweq12yt** [OpenDriver2/REDRIVER2#99]
**Describe the bug**
When going down the Havana secret area, turning the second to the left, walls vanish, become see-through, and collision totally breaks. Going straight forward slowly will eventually just drop you in one of the underground areas.

**To Reproduce**
1. Go to the Havana Secret Area as usual
2. When going down take the second to the left
3. Keep going down and when forced to take a left turn, it happens.

**Expected behavior**
The rest of the underground to load.

**Screenshots**
Printscreen does not work in fullscreen, and windowed is broken for me, so bear with phone photos:
- just after step 3.
![image](https://user-images.githubusercontent.com/45515587/116957189-9f5cbd80-ac6d-11eb-8768-8bbf8375ef0a.png)

- Eventually by exploring this void you can drop on the actual level bellow
![image](https://user-images.githubusercontent.com/45515587/116957226-bbf8f580-ac6d-11eb-9408-2f8cf211de0e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser: chrome

**Additional context**
Config.ini edited only to change controls and set to fullscreen

**Comment by SoapyMan** [comment]
This one was fixed in 85f60b3, check AppVeyor builds.
